### ISSUE TITLE
Remix 1.17.0 support

### ISSUE THREAD

**Issue by Klukies** [kiliman/remix-esbuild-analysis#1]
Hey 👋

I came across this package because I was interested in what my JS bundle contains.
During my search I came across [Kent's](https://kentcdodds.com/calls/01/136/whats-the-bundle-analysis-story-in-remix) call and your package which both should support analysis of the bundle.

However, with the current version of Remix (1.17.0 at the time of writing). I don't believe any of the provided solutions work with the current codebase. I'd love to help with this, but I'm not familiar with how the @remix-run/dev package works 😅

**Comment by kiliman** [comment]
Thanks. Yes, there have been a lot of changes to the dev compiler in recent releases. I haven't had a chance to update the patch to support this. When I have some free time, I'll create one.

**Comment by Klukies** [comment]
I'll be closing this off as this is now supported in the latest Remix release 😊
